services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: social_rankings
      POSTGRES_USER: social_rankings
      POSTGRES_PASSWORD: social_rankings
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    env_file:
      - .env.example
    environment:
      DATABASE_URL: postgresql+psycopg://social_rankings:social_rankings@db:5432/social_rankings
      API_KEY: 767ge4j63d
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
